import cv2
gray = cv2.imread("lena.bmp", 0)
color = cv2.imread("lenacolor.png")
print("图像GRAY属性：")
print("GRAY.SHAPE=",gray.shape)
print("GRAY.SIZE=",gray.size)
print("GRAY.dtype=",gray.dtype)
print("图像color属性：")
print("color.shape=",color.shape)
print("color.size:",color.size)
print("color.dtype=",color.dtype)