import numpy as np
x = np.arange(27)
# print(x)
x = np.reshape(x,(3,3,3))
# img = np.ones([2,4,3],dtype=np.uint8)
# print(x)
# print(x[0])
# print(x[0,1])
# print(x[:,:,0])
# print(x[0,:,:])
# print(x[:,0,:])
# print(x[:,:,0])
# print(img[1:2:1])
y = np.arange(24)
y = np.reshape(y,(2,4,3))
print(y)
print(y[:1])
print(y[0,:,:])